export const INCOME_GROUP = 'Income'
export const TRANSFER_GROUP = 'Transfer'
export const BORROWING_GROUP = 'Borrowing'
export const SAVINGS_GROUP = 'Savings'
export const ADJUSTMENT_GROUP = 'Adjustment'
